app = QtWidgets.QApplication(sys.argv)
win = QtWidgets.QWidget()
vbox = QtWidgets.QVBoxLayout()
VideoSignal1 = QtWidgets.QLabel()
btn_start = QtWidgets.QPushButton("카메라 켜기")
btn_stop = QtWidgets.QPushButton("카메라 끄기")
red_roi = QtWidgets.QPushButton("배회영역 설정")
vbox.addWidget(VideoSignal1)
vbox.addWidget(btn_start)
vbox.addWidget(btn_stop)
vbox.addWidget(red_roi)
win.setLayout(vbox)
win.show()
btn_start.clicked.connect(start)
btn_stop.clicked.connect(stop)
red_roi.clicked.connect(roi)
app.aboutToQuit.connect(onExit)
sys.exit(app.exec_())